### ISSUE TITLE
Help Needed?

### ISSUE THREAD

**Issue by decafboba** [shine-o/shine.engine.packet-sniffer#13]
Hey @SterlingAr, just wanted to see what areas of the Shine engine process you'd like help with. Great work so far!

**Comment by SterlingAr** [comment]
Hello, this repo is deprecated, i've moved the packet sniffer to the main emulator project, I invited you to it in case you want to see. And thanks! :D.

**Comment by decafboba** [comment]
Awesome, I will try to set up the repo and start experimenting soon! I'm rather new to server emulation but have tons of experience with golang / containers / kubernetes so maybe help architect a proper way to host this eventually.

Though I understand there is probably a ton of packet cracking to do for things like weapon attacks, monster aggro, etc.
